"""Initial

Revision ID: f10d916833f7
Revises:
Create Date: 2026-05-25 19:49:24.969219

"""

from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f10d916833f7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "code_chunks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("parent_file", sa.String(), nullable=False),
        sa.Column("chunk_type", sa.String(), nullable=False),
        sa.Column("chunk_name", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("file_signatures", sa.Text(), nullable=True),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "code_chunks_bm25_idx",
        "code_chunks",
        ["id", "chunk_name", "content", "file_signatures"],
        unique=False,
        postgresql_using="bm25",
        postgresql_with={"key_field": "id"},
    )
    op.create_index(
        "code_chunks_embedding_idx",
        "code_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 200},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "code_chunks_parent_file_idx", "code_chunks", ["parent_file"], unique=False
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("parent_file", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "document_chunks_bm25_idx",
        "document_chunks",
        ["id", "content", "parent_file"],
        unique=False,
        postgresql_using="bm25",
        postgresql_with={"key_field": "id"},
    )
    op.create_index(
        "document_chunks_embedding_idx",
        "document_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 200},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "document_chunks_parent_file_idx",
        "document_chunks",
        ["parent_file"],
        unique=False,
    )
    op.create_table(
        "indexed_documents",
        sa.Column("parent_file", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column(
            "indexed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("parent_file"),
    )
    op.create_table(
        "indexed_files",
        sa.Column("parent_file", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column(
            "indexed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("parent_file"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("indexed_files")
    op.drop_table("indexed_documents")
    op.drop_index("document_chunks_parent_file_idx", table_name="document_chunks")
    op.drop_index(
        "document_chunks_embedding_idx",
        table_name="document_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 200},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(
        "document_chunks_bm25_idx",
        table_name="document_chunks",
        postgresql_using="bm25",
        postgresql_with={"key_field": "id"},
    )
    op.drop_table("document_chunks")
    op.drop_index("code_chunks_parent_file_idx", table_name="code_chunks")
    op.drop_index(
        "code_chunks_embedding_idx",
        table_name="code_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 200},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(
        "code_chunks_bm25_idx",
        table_name="code_chunks",
        postgresql_using="bm25",
        postgresql_with={"key_field": "id"},
    )
    op.drop_table("code_chunks")
    # ### end Alembic commands ###
